# Generated by Django 4.1.3 on 2022-11-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0002_remove_artist_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='avg',
        ),
    ]
