# Generated by Django 4.1.3 on 2022-11-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0003_remove_album_rating_remove_magazine_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='critics.artist')),
                ('parent_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklist', to='critics.album')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
