# Generated by Django 4.1.3 on 2022-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0008_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
