# Generated by Django 4.1.3 on 2022-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0009_magazine_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='alt_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
