# Generated by Django 4.1.3 on 2022-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0010_alter_magazine_alt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='alt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
