# Generated by Django 4.1.3 on 2022-11-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0014_alter_album_options_remove_track_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['place_in_tracklist']},
        ),
        migrations.RemoveField(
            model_name='track',
            name='rating',
        ),
        migrations.AddField(
            model_name='track',
            name='place_in_tracklist',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReviewTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_review', to='critics.review')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='critics.track')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
