# Generated by Django 4.1.3 on 2022-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0015_alter_track_options_remove_track_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='featuring',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
