# Generated by Django 4.1.3 on 2022-11-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0016_track_featuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='parent_artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='critics.artist'),
            preserve_default=False,
        ),
    ]
