# Generated by Django 4.1.3 on 2022-11-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0018_remove_album_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='parent_artist',
        ),
    ]
