# Generated by Django 4.1.3 on 2022-11-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0004_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='count_review',
        ),
    ]
