# Generated by Django 4.1.3 on 2022-11-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0005_remove_artist_count_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='count_review',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='count_review',
        ),
    ]
