# Generated by Django 4.1.3 on 2022-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0006_remove_album_count_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
