# Generated by Django 4.1.3 on 2022-11-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0007_alter_track_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
    ]
