# Generated by Django 4.1.3 on 2022-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0011_alter_magazine_alt_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
