# Generated by Django 4.1.3 on 2022-11-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0013_alter_album_options_remove_album_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
