# Generated by Django 4.1.3 on 2022-11-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0019_remove_track_parent_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-id']},
        ),
    ]
