# Generated by Django 4.1.3 on 2022-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0020_alter_track_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('al', 'Álbum'), ('ar', 'Artista'), ('tr', 'Faixa'), ('ma', 'Revista')], default='al', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
