# Generated by Django 4.1.3 on 2022-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0021_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['place_in_tracklist']},
        ),
        migrations.AddField(
            model_name='track',
            name='get_rating',
            field=models.IntegerField(default=0),
        ),
    ]
