# Generated by Django 4.1.3 on 2022-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0022_alter_track_options_track_get_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='get_rating',
        ),
        migrations.AddField(
            model_name='album',
            name='get_rating',
            field=models.IntegerField(default=0),
        ),
    ]
