# Generated by Django 4.1.3 on 2022-11-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0023_remove_track_get_rating_album_get_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='get_rating',
        ),
    ]
